### ISSUE TITLE
Sugestões para o 'Tutorial GIT'

### ISSUE THREAD

**Issue by dbofmmbt** [llucasll/REL#1]
É necessário um detalhamento maior em relação ao uso de _'SSH Keys'_ para a verificação automatizada das credenciais do usuário. Isso é justificado pela rasa quantidade de conteúdos completos sobre essa autenticação. Até mesmo o tutorial feito pelo _GitHub_ passa a sensação de ser incompleto. Sugiro a separação desse tópico em um arquivo separado para melhor organização do conteúdo, ou mesmo a criação de um pequeno _SH-Script_ para tais comandos.

---
* ### [Aqui está o Link para o arquivo referenciado.](https://github.com/llucasll/tutorial/blob/master/Tutorial%20GIT.txt)
--------------------------

**Comment by llucasll** [comment]
Obrigado pelas sugestões, @eduardocanellas!
Dentro de alguns dias estaremos avaliando sua solicitação.

Att, llucasll.
